// Package tierdocs renders docs/tiers/ from setup/templates/profiles.json.
//
// A hardware tier is the single most load-bearing fact about an install — it sets
// the served window, the KV type, the backend template, which model stays resident
// and what media the box can generate — and until now it existed only as a JSON
// blob inside the installer. Anyone who downloaded the repo had no page to read for
// their own machine, which is a large part of why collaborators' installs drifted.
//
// The pages are GENERATED so they cannot drift from the profile table they
// describe: TestTierDocsAreCurrent regenerates in memory and fails if the checked-in
// tree differs. Edit profiles.json (or this generator), then `go generate ./...`.
package tierdocs

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/dmmdea/offload-harness/internal/mediaseat"
)

// Profile mirrors the fields setup/templates/profiles.json defines. Unknown keys
// are preserved in Extra so a new field surfaces in the docs as soon as it is
// added, instead of silently going undocumented.
type Profile struct {
	CtxSize        int             `json:"ctx_size"`
	KVType         string          `json:"kv_type"`
	AgentCtxTokens int             `json:"agent_ctx_tokens"`
	ResidentTier   string          `json:"resident_tier"`
	Include26B     bool            `json:"include_26b"`
	MoE26B         string          `json:"moe_26b"`
	FlashAttn      string          `json:"flash_attn"`
	Backend        string          `json:"backend"`
	DualResident   bool            `json:"dual_resident"`
	Notes          string          `json:"notes"`
	ConfigSeed     map[string]any  `json:"config_seed"`
	// MediaSeats are the ALIAS-backed media capabilities (vision / STT) the tier
	// serves. They are a separate axis from ConfigSeed — seats become llama-swap
	// models, seed keys become spawn-per-job bindings — and a page that showed only
	// the seed would understate what the tier delivers.
	MediaSeats []mediaseat.Seat `json:"media_seats"`
	Extra      json.RawMessage  `json:"-"`
}

type doc struct {
	Fields   map[string]string  `json:"_fields"`
	Profiles map[string]Profile `json:"profiles"`
}

// Render builds every tier page in memory. Exported so the staleness test can
// compare against the checked-in tree without running the binary.
func Render(root string) (map[string]string, error) {
	raw, err := os.ReadFile(filepath.Join(root, "setup", "templates", "profiles.json"))
	if err != nil {
		return nil, err
	}
	var d doc
	if err := json.Unmarshal(raw, &d); err != nil {
		return nil, fmt.Errorf("profiles.json: %w", err)
	}
	if len(d.Profiles) == 0 {
		return nil, fmt.Errorf("profiles.json has no profiles — the schema moved")
	}

	names := make([]string, 0, len(d.Profiles))
	for n := range d.Profiles {
		names = append(names, n)
	}
	sort.Strings(names)

	reports := findReports(root, names)
	out := map[string]string{
		filepath.Join("docs", "tiers", "README.md"): renderIndex(names, d.Profiles, reports),
	}
	for _, n := range names {
		out[filepath.Join("docs", "tiers", n+".md")] = renderTier(n, d.Profiles[n], reports[n])
	}
	return out, nil
}

// findReports maps a tier id to the capability reports checked in for it
// (docs/tiers/reports/<tier>-<host>.md). A tier with no report says so rather
// than pretending the page is complete.
func findReports(root string, names []string) map[string][]string {
	out := map[string][]string{}
	entries, err := os.ReadDir(filepath.Join(root, "docs", "tiers", "reports"))
	if err != nil {
		return out
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		// Longest tier id wins so "ampere-6" never claims "ampere-6x"'s report.
		best := ""
		for _, n := range names {
			if strings.HasPrefix(e.Name(), n+"-") && len(n) > len(best) {
				best = n
			}
		}
		if best != "" {
			out[best] = append(out[best], e.Name())
		}
	}
	for k := range out {
		sort.Strings(out[k])
	}
	return out
}

func renderIndex(names []string, profiles map[string]Profile, reports map[string][]string) string {
	var b strings.Builder
	b.WriteString(`<!-- GENERATED by cmd/gentiers from setup/templates/profiles.json — do not edit by hand; run: go generate ./... -->

# Hardware tiers

A **tier** is the hardware class an install is classified into. It decides the served
context window, the KV cache type, which llama-swap template renders, which model stays
resident, whether the 26B MoE is served at all, and what media this box can generate.
It is chosen once at install time and everything downstream follows from it.

Same tier, same capabilities — on any operating system. A tier is a HARDWARE class, not
a Windows class.

| tier | backend | ctx | KV | resident tier | 26B | media seat | report |
|---|---|---|---|---|---|---|---|
`)
	for _, n := range names {
		p := profiles[n]
		media := "—"
		if len(p.ConfigSeed) > 0 {
			media = mediaSummary(p.ConfigSeed)
		}
		if n := len(p.MediaSeats); n > 0 {
			kinds := make([]string, 0, n)
			for _, s := range p.MediaSeats {
				kinds = append(kinds, s.Kind)
			}
			sort.Strings(kinds)
			seats := "+ " + strings.Join(kinds, "/") + " seat"
			if media == "—" {
				media = seats[2:]
			} else {
				media += " " + seats
			}
		}
		rep := "—"
		if len(reports[n]) > 0 {
			rep = fmt.Sprintf("[%d](%s)", len(reports[n]), "reports/"+reports[n][0])
		}
		fmt.Fprintf(&b, "| [%s](%s.md) | %s | %d | %s | %s | %s | %s | %s |\n",
			n, n, dash(p.Backend), p.CtxSize, dash(p.KVType), dash(p.ResidentTier), moe(p), media, rep)
	}

	b.WriteString(`
## Which tier am I?

The installer classifies the machine and writes the answer to
` + "`$OFFLOAD_HOME/installed.json`" + `. To read it back — along with everything the tier
actually delivers on THIS box:

` + "```" + `
local-offload report --out capability-report.md
` + "```" + `

That is the document to attach when asking for help, and the one to send when someone
asks what a machine can do. It is **read-only**: no model is loaded, no GPU work is
queued, nothing changes. It reports the harness version, the config file actually
loaded, the tier, every configured model alias measured against the live
` + "`/v1/models`" + `, and every media route with its derived verdict:

| verdict | meaning | a fault? |
|---|---|---|
| ` + "`CONFIGURED`" + ` | bound, and every file it names exists | no |
| ` + "`NOT CONFIGURED`" + ` | no binding on this box; the task defers by design | no |
| ` + "`BOUND-BUT-MISSING`" + ` | the config names a file that is not there | **yes** |

Only the last is listed under **Needs attention**. A route a box never bound is a
legitimate machine, not a defect.

Checked-in reports live in [reports/](reports/) and are examples to compare against, not
a claim about your hardware.

## Reading a tier page

Each page states the serving parameters the tier renders, whether the tier ships a media
configuration (` + "`config_seed`" + `), and the operator notes recorded for it — many of
which are measurements taken on real hardware, including the reasons a tempting change was
deliberately NOT made.

A tier with **no media seat** serves text only: image/video/audio routes fall back to the
shipped defaults, which means they report ` + "`NOT CONFIGURED`" + ` (or
` + "`BOUND-BUT-MISSING`" + ` if a default script path does not exist on that machine)
until the operator binds them. That gap is tracked in the install-architecture plan.

## Source

- [setup/templates/profiles.json](../../setup/templates/profiles.json) — the table these pages render from
- [setup/SETUP-AGENT.md](../../setup/SETUP-AGENT.md) — the install runbook
- [../systems/setup-installer.md](../systems/setup-installer.md) — how classification and rendering work
`)
	return b.String()
}

func renderTier(name string, p Profile, reports []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<!-- GENERATED by cmd/gentiers from setup/templates/profiles.json — do not edit by hand; run: go generate ./... -->\n\n# Tier `%s`\n\n", name)

	b.WriteString("## Serving\n\n| setting | value | what it controls |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| backend | `%s` | which `llama-swap.*.yaml` template renders |\n", dash(p.Backend))
	fmt.Fprintf(&b, "| ctx_size | %d | the served window (`--ctx-size`) |\n", p.CtxSize)
	fmt.Fprintf(&b, "| kv_type | `%s` | `--cache-type-k/v`, kept symmetric |\n", dash(p.KVType))
	fmt.Fprintf(&b, "| flash_attn | `%s` | `--flash-attn` (required for a q8_0 V cache) |\n", dash(p.FlashAttn))
	fmt.Fprintf(&b, "| resident_tier | `%s` | the model that stays hot and is the agent's default |\n", dash(p.ResidentTier))
	fmt.Fprintf(&b, "| agent_ctx_tokens | %d | the agent's `-ctx-tokens` compaction budget |\n", p.AgentCtxTokens)
	fmt.Fprintf(&b, "| 26B-A4B | %s | whether the 26B MoE is served, and where its experts live |\n", moe(p))
	if p.DualResident {
		b.WriteString("| dual_resident | `true` | two models stay resident; no shared exclusive swap group |\n")
	}

	b.WriteString("\n## Media\n\n")
	if len(p.MediaSeats) > 0 {
		b.WriteString("This tier serves these media **seats** — models in its own llama-swap config, rendered\n" +
			"at install time. Each seat also produces the harness config binding that routes to it, so a\n" +
			"binding can never name a seat that was not rendered:\n\n" +
			"| seat | kind | binds | model | residency |\n|---|---|---|---|---|\n")
		for _, s := range p.MediaSeats {
			bind := "`vision_model`"
			if s.Kind == mediaseat.KindSTT {
				bind = "`stt_model`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | `%s` | %s |\n", s.Name, s.Kind, bind, s.Model, s.Residency)
		}
		b.WriteString("\nA seat still needs its weights on the box — model downloads stay out-of-band, as with\nevery seed.\n\n")
	}
	if len(p.ConfigSeed) == 0 && len(p.MediaSeats) > 0 {
		// Seats but no seed: a real combination, and the seed branch below would
		// print an empty table under a heading claiming bindings exist.
		b.WriteString("It ships no file-backed media seed, so `generate_image` / `generate_video` /\n" +
			"`generate_audio` / `run_graph` report `NOT CONFIGURED` until an operator binds them.\n")
	} else if len(p.ConfigSeed) == 0 {
		b.WriteString("**This tier ships no media configuration.** It serves text only until an operator binds\n" +
			"the media routes by hand, so `generate_image`, `generate_video`, `generate_audio` and\n" +
			"`run_graph` will report `NOT CONFIGURED` — or `BOUND-BUT-MISSING` where a shipped default\n" +
			"script path does not exist on the machine. Run `local-offload doctor` to see which.\n")
	} else {
		b.WriteString("The installer seeds this tier's media bindings (`config_seed`):\n\n| key | value |\n|---|---|\n")
		keys := make([]string, 0, len(p.ConfigSeed))
		for k := range p.ConfigSeed {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "| `%s` | `%s` |\n", k, valueString(p.ConfigSeed[k]))
		}
		b.WriteString("\n`__OFFLOAD_HOME__` is replaced with the install root at render time.\n")
	}

	if strings.TrimSpace(p.Notes) != "" {
		b.WriteString("\n## Operator notes\n\nRecorded with the profile — several are measurements from real hardware,\nincluding reasons a tempting change was deliberately not made.\n\n> " +
			strings.ReplaceAll(strings.TrimSpace(p.Notes), "\n", "\n> ") + "\n")
	}

	b.WriteString("\n## Capability report\n\nWhat this tier delivers on a SPECIFIC machine is a question only that machine can answer:\n\n```\nlocal-offload report --out capability-report.md\n```\n\n")
	if len(reports) == 0 {
		b.WriteString("No report is checked in for this tier yet. If you run this tier, yours is welcome —\nit is read-only output and it is how the tier gets documented for the next person.\n")
	} else {
		b.WriteString("Checked-in examples (real machines, read-only output):\n\n")
		for _, r := range reports {
			fmt.Fprintf(&b, "- [%s](reports/%s)\n", strings.TrimSuffix(r, ".md"), r)
		}
	}
	fmt.Fprintf(&b, "\n---\n\n[All tiers](README.md) · [profiles.json](../../setup/templates/profiles.json) · [installer](../systems/setup-installer.md)\n")
	return b.String()
}

func mediaSummary(seed map[string]any) string {
	if e, ok := seed["imagegen_engine"].(string); ok && e != "" {
		if f, ok := seed["imagegen_family"].(string); ok && f != "" {
			return fmt.Sprintf("`%s` (%s)", e, f)
		}
		return "`" + e + "`"
	}
	if f, ok := seed["imagegen_family"].(string); ok && f != "" {
		return "comfyui (" + f + ")"
	}
	return "yes"
}

func moe(p Profile) string {
	if !p.Include26B || p.MoE26B == "drop" || p.MoE26B == "" {
		return "dropped"
	}
	return "`" + p.MoE26B + "`"
}

func valueString(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case []any:
		parts := make([]string, 0, len(t))
		for _, e := range t {
			parts = append(parts, fmt.Sprint(e))
		}
		return strings.Join(parts, " ")
	case float64:
		if t == float64(int64(t)) {
			return fmt.Sprintf("%d", int64(t))
		}
		return fmt.Sprintf("%g", t)
	default:
		return fmt.Sprint(v)
	}
}

func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}
