// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCHED (wave E): /metrics answers Prometheus exposition text, not JSON, and
// answers 503 when llama-swap was started without monitoring. The generated
// read path decoded the 200 body as JSON (exit 5) and would have raised the 503
// as a server error. See .printing-press-patches/internal-cli-activity_prometheus.go.md.

package cli

import (
	"fmt"
	"io"
	"net/http"

	"github.com/spf13/cobra"
)

func newActivityPrometheusCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "prometheus",
		Short: "Prometheus exposition of proxy metrics.",
		Long: `Prometheus exposition of proxy metrics.

llama-swap serves /metrics only when it was started with monitoring enabled.
Without it the proxy answers 503, which this command reports as
metrics_enabled:false and exits 0 — a switched-off feature is a fact about the
deployment, not a failure to retry.

Exit codes: 0 success (including monitoring-disabled), 4 server unreachable.`,
		Example: "  llamaswap-pp-cli activity prometheus",
		Annotations: map[string]string{
			"pp:endpoint":         "activity.prometheus",
			"pp:method":           "GET",
			"pp:path":             "/metrics",
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,4",
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return writeDryRun(cmd.OutOrStdout(), flags, "activity prometheus")
			}
			resp, err := rawTextGet(cmd.Context(), flags, "/metrics")
			if err != nil {
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s/metrics: %w", resp.BaseURL, err))
			}
			switch {
			case resp.Status == http.StatusOK:
				payload := newRawTextMetricsPayload(resp)
				return mcEmit(cmd, flags, payload, func(w io.Writer) {
					rawTextPrintBody(w, resp.Body)
				})
			case resp.Status == http.StatusServiceUnavailable:
				payload := newRawTextMetricsOffPayload(resp.Status, rawTextPrometheusOffReason)
				return mcEmit(cmd, flags, payload, func(w io.Writer) {
					fmt.Fprintf(w, "no metrics: %s\n", payload.Reason)
				})
			default:
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s/metrics returned HTTP %d", resp.BaseURL, resp.Status))
			}
		},
	}

	return cmd
}
