// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newActivityCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "activity",
		Short:       "Request history and performance metrics kept in the proxy's memory (lost on restart).",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newActivityLogCmd(flags))
	cmd.AddCommand(newActivityPerformanceCmd(flags))
	cmd.AddCommand(newActivityPrometheusCmd(flags))
	cmd.AddCommand(newActivityStatsCmd(flags))
	return cmd
}
