// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCHED (wave E): /logs answers text/plain, not JSON. The generated read path
// decoded it as JSON and failed with exit 5 against a healthy proxy. The
// `triage` subcommand (logs_triage.go, attached in glue_common.go) already
// fetched the buffer as text; this makes the parent do the same.
// See .printing-press-patches/internal-cli-promoted_logs.go.md.

package cli

import (
	"fmt"
	"io"
	"net/http"

	"github.com/spf13/cobra"
)

func newLogsPromotedCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:     "logs",
		Short:   "Buffered recent logs as plain text (proxy + upstream stdout/stderr interleaved).",
		Long:    "Buffered recent logs as plain text (proxy + upstream stdout/stderr interleaved).",
		Example: "  llamaswap-pp-cli logs",
		Annotations: map[string]string{
			"pp:endpoint":         "logs.get",
			"pp:method":           "GET",
			"pp:path":             "/logs",
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,4",
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return writeDryRun(cmd.OutOrStdout(), flags, "logs")
			}
			resp, err := rawTextGet(cmd.Context(), flags, "/logs")
			if err != nil {
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s/logs: %w", resp.BaseURL, err))
			}
			if resp.Status != http.StatusOK {
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s/logs returned HTTP %d", resp.BaseURL, resp.Status))
			}
			payload := newRawTextBodyPayload(resp)
			return mcEmit(cmd, flags, payload, func(w io.Writer) {
				rawTextPrintBody(w, resp.Body)
			})
		},
	}

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
