// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newServerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "server",
		Short:       "Proxy-level health, version, and hardware identity.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newServerHardwareCmd(flags))
	cmd.AddCommand(newServerHealthCmd(flags))
	cmd.AddCommand(newServerVersionCmd(flags))
	return cmd
}
