// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCHED (wave E): /health answers the literal string "OK", not JSON. The
// generated read path decoded it as JSON and failed with exit 5 against a
// healthy proxy. See .printing-press-patches/internal-cli-server_health.go.md.

package cli

import (
	"fmt"
	"io"
	"net/http"

	"github.com/spf13/cobra"
)

func newServerHealthCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:     "health",
		Short:   "Liveness of the llama-swap proxy itself (plain 'OK').",
		Example: "  llamaswap-pp-cli server health",
		Annotations: map[string]string{
			"pp:endpoint":         "server.health",
			"pp:method":           "GET",
			"pp:path":             "/health",
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,4",
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return writeDryRun(cmd.OutOrStdout(), flags, "server health")
			}
			resp, err := rawTextGet(cmd.Context(), flags, "/health")
			if err != nil {
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s/health: %w", resp.BaseURL, err))
			}
			if resp.Status != http.StatusOK {
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s/health returned HTTP %d", resp.BaseURL, resp.Status))
			}
			payload := newRawTextHealthPayload(resp)
			return mcEmit(cmd, flags, payload, func(w io.Writer) {
				fmt.Fprintf(w, "%s  (%s, %d ms)\n", payload.Body, resp.BaseURL, payload.LatencyMS)
			})
		},
	}

	return cmd
}
