// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// PATCHED (wave E): /upstream/{model}/metrics answers Prometheus exposition
// text, not JSON, and answers 501/404 when the seat's llama-server was started
// without --metrics. The generated read path decoded the body as JSON and
// raised the seat-flag absence as a not-found error.
// See .printing-press-patches/internal-cli-upstream_metrics.go.md.

package cli

import (
	"fmt"
	"io"
	"net/http"

	"github.com/spf13/cobra"
)

func newUpstreamMetricsCmd(flags *rootFlags) *cobra.Command {
	var flagModel string

	cmd := &cobra.Command{
		Use:   "metrics",
		Short: "Per-model llama-server Prometheus metrics (needs --metrics on the seat; 501/404 otherwise).",
		Long: `Per-model llama-server Prometheus metrics.

llama.cpp's server exposes /metrics only when the seat was launched with
--metrics. Without the flag it answers 501 (some builds 404), which this
command reports as metrics_enabled:false and exits 0 — an absent seat flag is a
fact about the configuration, not a failure to retry. This matches the
convention the rest of this CLI already uses: hardware 404 means the feature is
absent, prometheus 503 means monitoring is off.

Exit codes: 0 success (including metrics-not-enabled), 2 usage, 4 server
unreachable, 5 unexpected API status, 27 upstream 5xx.`,
		Example:     "  llamaswap-pp-cli upstream metrics --model embeddinggemma",
		Annotations: map[string]string{"pp:endpoint": "upstream.metrics", "pp:method": "GET", "pp:path": "/upstream/{model}/metrics", "mcp:read-only": "true", "pp:happy-args": "--model;embeddinggemma", "pp:typed-exit-codes": "0,2,4,5,27"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			// Machine callers (--json/--agent, which sets asJSON) get a usage
			// error + exit 2 instead of silent exit-0 help, so an incomplete
			// invocation is never mistaken for success.
			if !hasChangedLocalFlags(cmd) && len(args) == 0 && !flags.dryRun {
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "requires input",
						"usage": cmd.CommandPath() + " --help",
					}, flags); printErr != nil {
						return printErr
					}
					return usageErr(fmt.Errorf("%q requires input; run %q for usage", cmd.CommandPath(), cmd.CommandPath()+" --help"))
				}
				return cmd.Help()
			}
			if !cmd.Flags().Changed("model") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "model")
			}
			if dryRunOK(flags) {
				return writeDryRun(cmd.OutOrStdout(), flags, "upstream metrics")
			}
			path := replacePathParam("/upstream/{model}/metrics", "model", formatCLIParamValue(flagModel))
			resp, err := rawTextGet(cmd.Context(), flags, path)
			if err != nil {
				return spineExitErr(ExitServerUnreachable,
					fmt.Errorf("GET %s%s: %w", resp.BaseURL, path, err))
			}
			switch {
			case resp.Status == http.StatusOK:
				payload := newRawTextMetricsPayload(resp)
				return mcEmit(cmd, flags, payload, func(w io.Writer) {
					rawTextPrintBody(w, resp.Body)
				})
			case resp.Status == http.StatusNotImplemented || resp.Status == http.StatusNotFound:
				payload := newRawTextMetricsOffPayload(resp.Status, rawTextUpstreamMetricsOffReason)
				return mcEmit(cmd, flags, payload, func(w io.Writer) {
					fmt.Fprintf(w, "no metrics for %s: %s\n", flagModel, payload.Reason)
				})
			case resp.Status >= 500:
				return spineExitErr(ExitUpstream5xx,
					fmt.Errorf("GET %s%s returned HTTP %d", resp.BaseURL, path, resp.Status))
			default:
				return apiErr(fmt.Errorf("GET %s%s returned HTTP %d", resp.BaseURL, path, resp.Status))
			}
		},
	}
	cmd.Flags().StringVar(&flagModel, "model", "", "")

	return cmd
}
