// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUpstreamCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "upstream",
		Short:       "Passthrough to one model's full llama.cpp llama-server API.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUpstreamApplyTemplateCmd(flags))
	cmd.AddCommand(newUpstreamDetokenizeCmd(flags))
	cmd.AddCommand(newUpstreamEmbeddingsCmd(flags))
	cmd.AddCommand(newUpstreamHealthCmd(flags))
	cmd.AddCommand(newUpstreamLoraAdaptersCmd(flags))
	cmd.AddCommand(newUpstreamLoraSetCmd(flags))
	cmd.AddCommand(newUpstreamMetricsCmd(flags))
	cmd.AddCommand(newUpstreamPropsCmd(flags))
	cmd.AddCommand(newUpstreamRerankCmd(flags))
	cmd.AddCommand(newUpstreamSlotsCmd(flags))
	cmd.AddCommand(newUpstreamTokenizeCmd(flags))
	return cmd
}
