// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newObjectinfoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "objectinfo",
		Short:       "The live node schema — the authority on class names and valid input values.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newObjectinfoAllCmd(flags))
	cmd.AddCommand(newObjectinfoGetCmd(flags))
	return cmd
}
