// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUserdataCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "userdata",
		Short:       "Server-side user files, including saved workflows.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUserdataGetCmd(flags))
	cmd.AddCommand(newUserdataPutCmd(flags))
	return cmd
}
