// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Three tools cover the entire API: comfyui_search to discover endpoints,
// comfyui_get to inspect one GET endpoint, and comfyui_execute to invoke one.
// This collapses the whole ComfyUI HTTP surface (13 endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search, get, and execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	"comfyui-pp-cli/internal/cli"
	"comfyui-pp-cli/internal/mcp/bound"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the agent-facing tools that cover
// the whole API surface. Called from RegisterTools in place of the per-endpoint
// registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("comfyui_search",
			mcplib.WithDescription("Search the comfyui API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
			mcplib.WithRawOutputSchema(json.RawMessage(codeOrchSearchOutputSchema)),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("comfyui_get",
			mcplib.WithDescription("Get metadata for one GET endpoint by its endpoint_id (from comfyui_search). This registry-only lookup never calls the API."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("GET endpoint identifier returned by comfyui_search (e.g., \"history.list\").")),
			mcplib.WithRawOutputSchema(json.RawMessage(codeOrchGetOutputSchema)),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchGet,
	)

	s.AddTool(
		mcplib.NewTool("comfyui_execute",
			mcplib.WithDescription("Execute one comfyui API endpoint by its endpoint_id (from comfyui_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by comfyui_search (e.g., \"history.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
			mcplib.WithRawOutputSchema(json.RawMessage(codeOrchExecuteOutputSchema)),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// registry tools need at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID      string
	Method  string
	Path    string
	Tier    string
	Summary string
	// Positional carries the endpoint's real `{name}` path placeholders.
	// Populating it is what makes path substitution actually happen:
	// handleCodeOrchExecute only rewrites `{name}` for names listed here, so
	// an endpoint left with an empty Positional ships its literal template
	// (".../history/{prompt_id}") to the server and 404s.
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// Keep declared headers out of query/body routing so execution sends them
	// through the request-header map.
	HeaderParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	Mutating    bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
	Default    string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via comfyui_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "history.get",
		Method:         "GET",
		Path:           "/history/{prompt_id}",
		Summary:        "Full record for one prompt: status (status_str, completed), the messages array carrying execution_start / execution_success / execution_error timestamps in milliseconds, and the outputs map. The timestamp delta is the ONLY honest source of per-prompt duration — scraping 'Prompt executed in N seconds' from the server log returns a stale line when the current run has not finished, and scraping an s/it progress bar returns a transient intra-run sample, not a rate. Required: prompt_id.",
		Positional:     []string{"prompt_id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("history", "get", "Full record for one prompt: status (status_str, completed), the messages array carrying execution_start / execution_success / execution_error timestamps in milliseconds, and the outputs map. The timestamp delta is the ONLY honest source of per-prompt duration — scraping 'Prompt executed in N seconds' from the server log returns a stale line when the current run has not finished, and scraping an s/it progress bar returns a transient intra-run sample, not a rate. Required: prompt_id.", "/history/{prompt_id}"),
	},
	{
		ID:             "history.list",
		Method:         "GET",
		Path:           "/history",
		Summary:        "List the ComfyUI server's completed prompt records, newest last. Optional: max_items caps how many records come back. Each record carries its status (status_str, completed), the messages array holding execution_start / execution_success / execution_error timestamps in milliseconds, and the outputs map — that timestamp pair is the only honest source of per-prompt duration. Use history.get when you already have a prompt_id. This history lives in the server's RAM and is destroyed on every restart, so read it before restarting.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "max_items", WireName: "max_items"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("history", "list", "List the ComfyUI server's completed prompt records, newest last. Optional: max_items caps how many records come back. Each record carries its status (status_str, completed), the messages array holding execution_start / execution_success / execution_error timestamps in milliseconds, and the outputs map — that timestamp pair is the only honest source of per-prompt duration. Use history.get when you already have a prompt_id. This history lives in the server's RAM and is destroyed on every restart, so read it before restarting.", "/history"),
	},
	{
		ID:             "objectinfo.all",
		Method:         "GET",
		Path:           "/object_info",
		Summary:        "List every node class registered on the running server together with its full input schema. This is the authority on valid class_type strings and on the COMBO option values a loader will actually accept — a graph that names a class or value absent here fails validation. Takes no parameters and returns the entire schema keyed by class name, which on a real box is over a thousand classes; prefer objectinfo.get when you already know which class you need.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("objectinfo", "all", "List every node class registered on the running server together with its full input schema. This is the authority on valid class_type strings and on the COMBO option values a loader will actually accept — a graph that names a class or value absent here fails validation. Takes no parameters and returns the entire schema keyed by class name, which on a real box is over a thousand classes; prefer objectinfo.get when you already know which class you need.", "/object_info"),
	},
	{
		ID:             "objectinfo.get",
		Method:         "GET",
		Path:           "/object_info/{class_type}",
		Summary:        "Schema for one node class. Loader COMBO options live at index 1 of the input tuple as {'options' -> [...]}, NOT at index 0 — index 0 is the type string. An EMPTY options list means the model CLASS is unregistered (missing extra_model_paths.yaml key), not that the file is missing. Required: class_type.",
		Positional:     []string{"class_type"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("objectinfo", "get", "Schema for one node class. Loader COMBO options live at index 1 of the input tuple as {'options' -> [...]}, NOT at index 0 — index 0 is the type string. An EMPTY options list means the model CLASS is unregistered (missing extra_model_paths.yaml key), not that the file is missing. Required: class_type.", "/object_info/{class_type}"),
	},
	{
		ID:             "prompt.submit",
		Method:         "POST",
		Path:           "/prompt",
		Summary:        "Queue an API-format graph. Returns {prompt_id, number, node_errors} on success. On validation failure returns HTTP 400 with an error object plus a node_errors map keyed by node id — that detail is the whole diagnostic and must be surfaced verbatim, never summarised.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("prompt", "submit", "Queue an API-format graph. Returns {prompt_id, number, node_errors} on success. On validation failure returns HTTP 400 with an error object plus a node_errors map keyed by node id — that detail is the whole diagnostic and must be surfaced verbatim, never summarised.", "/prompt"),
	},
	{
		ID:             "queue.clear",
		Method:         "POST",
		Path:           "/queue",
		Summary:        "Clear pending work from the ComfyUI render queue. Send clear: true to wipe every pending item, or delete: ['<prompt_id>', ...] to drop specific pending prompts; a call carrying neither field posts an empty body and the server does nothing. This does NOT stop the prompt already executing — use queue.interrupt for that. Call queue.get first to see what is actually pending.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("queue", "clear", "Clear pending work from the ComfyUI render queue. Send clear: true to wipe every pending item, or delete: ['<prompt_id>', ...] to drop specific pending prompts; a call carrying neither field posts an empty body and the server does nothing. This does NOT stop the prompt already executing — use queue.interrupt for that. Call queue.get first to see what is actually pending.", "/queue"),
	},
	{
		ID:             "queue.get",
		Method:         "GET",
		Path:           "/queue",
		Summary:        "Returns {queue_running, queue_pending}. A non-empty queue_running with an idle GPU means the job is in a non-sampling stage (VAE decode, video assembly), not stalled.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("queue", "get", "Returns {queue_running, queue_pending}. A non-empty queue_running with an idle GPU means the job is in a non-sampling stage (VAE decode, video assembly), not stalled.", "/queue"),
	},
	{
		ID:             "queue.interrupt",
		Method:         "POST",
		Path:           "/interrupt",
		Summary:        "Interrupt the currently executing prompt. Does not clear pending items.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("queue", "interrupt", "Interrupt the currently executing prompt. Does not clear pending items.", "/interrupt"),
	},
	{
		ID:             "system.stats",
		Method:         "GET",
		Path:           "/system_stats",
		Summary:        "ComfyUI version, python version, and per-device vram_total / vram_free. Device ordering here is torch ordering, which can be the INVERSE of nvidia-smi ordering — trust this endpoint for cuda:N identity, not nvidia-smi index.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "stats", "ComfyUI version, python version, and per-device vram_total / vram_free. Device ordering here is torch ordering, which can be the INVERSE of nvidia-smi ordering — trust this endpoint for cuda:N identity, not nvidia-smi index.", "/system_stats"),
	},
	{
		ID:             "upload.image",
		Method:         "POST",
		Path:           "/upload/image",
		Summary:        "Upload an image into ComfyUI's input dir. LoadImage takes a FILENAME inside that dir, never an absolute host path — passing an absolute path fails validation with 'Invalid image file'.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("upload", "image", "Upload an image into ComfyUI's input dir. LoadImage takes a FILENAME inside that dir, never an absolute host path — passing an absolute path fails validation with 'Invalid image file'.", "/upload/image"),
	},
	{
		ID:             "userdata.get",
		Method:         "GET",
		Path:           "/userdata/{file}",
		Summary:        "Read a user file. Workflow paths are URL-encoded, e.g. workflows%2Fname.json. Required: file.",
		Positional:     []string{"file"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("userdata", "get", "Read a user file. Workflow paths are URL-encoded, e.g. workflows%2Fname.json. Required: file.", "/userdata/{file}"),
	},
	{
		ID:             "userdata.put",
		Method:         "POST",
		Path:           "/userdata/{file}",
		Summary:        "Write a user file, creating parent dirs. Pass overwrite=true to replace. Required: file. Optional: overwrite.",
		Positional:     []string{"file"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "overwrite", WireName: "overwrite"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("userdata", "put", "Write a user file, creating parent dirs. Pass overwrite=true to replace. Required: file. Optional: overwrite.", "/userdata/{file}"),
	},
	{
		ID:             "view.get",
		Method:         "GET",
		Path:           "/view",
		Summary:        "Fetch one file the server produced or holds by name. Required: filename. Optional: subfolder, and type — one of output, input, or temp, which selects the directory the name is resolved against. Returns that file's contents, so send it to a path rather than into a transcript. Use history.get or the outputs a prompt reported to learn the filename and subfolder to pass here.",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "filename", WireName: "filename"}, {PublicName: "subfolder", WireName: "subfolder"}, {PublicName: "type", WireName: "type"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("view", "get", "Fetch one file the server produced or holds by name. Required: filename. Optional: subfolder, and type — one of output, input, or temp, which selects the directory the name is resolved against. Returns that file's contents, so send it to a path rather than into a transcript. Use history.get or the outputs a prompt reported to learn the filename and subfolder to pass here.", "/view"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func codeOrchEndpointMetadata(ep *codeOrchEndpoint) map[string]any {
	out := map[string]any{
		"endpoint_id": ep.ID,
		"method":      ep.Method,
		"path":        ep.Path,
		"summary":     ep.Summary,
	}
	return out
}

func findCodeOrchEndpoint(id string) *codeOrchEndpoint {
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			return &codeOrchEndpoints[i]
		}
	}
	return nil
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		item := codeOrchEndpointMetadata(r.ep)
		item["score"] = r.score
		out = append(out, item)
	}
	payload := map[string]any{"count": len(out), "results": out}
	text, err := bound.JSON(payload)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding search results: %v", err)), nil
	}
	// structuredContent carries the same payload the text content renders, so a
	// host that reads the declared outputSchema never has to re-parse the text.
	return mcplib.NewToolResultStructured(payload, text), nil
}

func handleCodeOrchGet(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call comfyui_search first)"), nil
	}
	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call comfyui_search to discover valid ids", id)), nil
	}
	if ep.Method != "GET" {
		return mcplib.NewToolResultError(fmt.Sprintf("endpoint_id %q is %s, but comfyui_get only permits GET endpoints", id, ep.Method)), nil
	}
	payload := codeOrchEndpointMetadata(ep)
	text, err := bound.JSON(payload)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding endpoint metadata: %v", err)), nil
	}
	return mcplib.NewToolResultStructured(payload, text), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call comfyui_search first)"), nil
	}

	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call comfyui_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, platformSession, err := newMCPClient(ctx)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	if platformSession != nil {
		defer platformSession.ZeroCredentials()
	}
	if err := cli.AdoptMCPOutputSemantics(platformSession, params); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok && strings.Contains(path, "{"+p+"}") {
			path = strings.ReplaceAll(path, "{"+p+"}", mcpPathValue(v))
			delete(params, p)
		}
	}

	hdrs := make(map[string]string, len(ep.HeaderOverrides)+len(ep.HeaderParams))
	for k, v := range ep.HeaderOverrides {
		hdrs[k] = v
	}
	for _, binding := range ep.HeaderParams {
		if binding.Default != "" {
			hdrs[binding.WireName] = binding.Default
		}
		for _, key := range []string{binding.PublicName, binding.WireName} {
			if v, ok := params[key]; ok {
				hdrs[binding.WireName] = formatMCPParamValue(v)
				delete(params, key)
				break
			}
		}
	}
	if len(hdrs) == 0 {
		hdrs = nil
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. overwrite on
		// POST /userdata/{file}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			if ep.Mutating {
				data, err = c.GetMutatingWithHeaders(ctx, path, query, hdrs)
			} else {
				data, err = c.GetWithHeaders(ctx, path, query, hdrs)
			}
		} else {
			if ep.Mutating {
				data, err = c.GetMutating(ctx, path, query)
			} else {
				data, err = c.Get(ctx, path, query)
			}
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	text := bound.EndpointResponse(ep.Method, data)
	if platformSession != nil {
		text = bound.WithMetadata(text, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultStructured(codeOrchExecuteStructured(ep, path, text), text), nil
}

// codeOrchInlineBodyMax caps how much response body codeOrchExecuteStructured
// will mirror into structuredContent. The text content already carries the
// whole bounded body, so above this size the duplicate is dropped rather than
// pushing one tool result to twice bound.MaxBytes on the wire.
const codeOrchInlineBodyMax = bound.MaxBytes / 2

// codeOrchExecuteStructured builds the structuredContent envelope declared by
// comfyui_execute's outputSchema. It reports the request that was actually
// issued — path after placeholder substitution and query assembly — alongside
// the response body. The body is mirrored as parsed JSON when it is JSON, as
// verbatim text when it is not (ComfyUI's /view returns file bytes), and
// omitted with body_omitted set when it exceeds codeOrchInlineBodyMax.
func codeOrchExecuteStructured(ep *codeOrchEndpoint, path, text string) map[string]any {
	out := map[string]any{
		"endpoint_id": ep.ID,
		"method":      ep.Method,
		"path":        path,
		"body_bytes":  len(text),
	}
	if len(text) > codeOrchInlineBodyMax {
		out["body_omitted"] = true
		return out
	}
	var body any
	if json.Unmarshal([]byte(text), &body) == nil {
		out["body"] = body
		return out
	}
	out["body_text"] = text
	return out
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 400) instead of
// silently sending the wrong shape or a partial write — a queued render is
// never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, formatMCPParamValue(v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
