// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — intent handlers.
//
// Intents are higher-level MCP tools that compose multiple endpoint calls
// or expose curated recipe commands with useful flag defaults.
// Rather than forcing an agent to stitch primitives like get_thread +
// create_issue + link_attachment, a single create_issue_from_thread tool
// accepts the top-level input, calls each endpoint in sequence, resolves
// bindings between steps, and returns the final captured value.
//
// Each intent is emitted as a handler registered alongside (or in place of,
// when MCP.EndpointTools == "hidden") the raw endpoint-mirror tools.

package mcp

import (
	"context"
	"fmt"
	"strings"

	"comfyui-pp-cli/internal/mcp/cobratree"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterIntents adds generated intent tools to the MCP server.
// This is called from RegisterTools when spec intents or recipe-lifted intents exist.
func RegisterIntents(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("diagnose_an_invisible_model",
			mcplib.WithDescription("Separates unregistered model class from not-listed and no-such-input, each with its own remedy, instead of reporting a generic missing file."),
			mcplib.WithString("domain", mcplib.Required(), mcplib.Description("Override the recipe's positional domain value.")),
		),
		handleDiagnoseAnInvisibleModel,
	)
	s.AddTool(
		mcplib.NewTool("preflight_a_graph_offline",
			mcplib.WithDescription("The server has no validate-only endpoint, so this is the only dry run that does not consume a queue slot."),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Override the recipe's positional path value.")),
		),
		handlePreflightAGraphOffline,
	)
	s.AddTool(
		mcplib.NewTool("patch_a_graph_without_silently_hitting_the_wrong_node",
			mcplib.WithDescription("Refuses the write when node 6 no longer holds the expected class, which is how a template revision fails loudly rather than quietly."),
			mcplib.WithString("path", mcplib.Required(), mcplib.Description("Override the recipe's positional path value.")),
		),
		handlePatchAGraphWithoutSilentlyHittingTheWrongNode,
	)
}

// handleDiagnoseAnInvisibleModel runs the diagnose_an_invisible_model recipe intent: Separates unregistered model class from not-listed and no-such-input, each with its own remedy, instead of reporting a generic missing file.
func handleDiagnoseAnInvisibleModel(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	if recipeCLIPathErr != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v", recipeCLIPathErr)), nil
	}

	input := req.GetArguments()
	args := []string{}
	args = append(args, "models")
	args = append(args, "why")
	var missingDomain bool
	args, missingDomain = appendRecipePositional(args, input["domain"], true)
	if missingDomain {
		return mcplib.NewToolResultError("domain is required"), nil
	}
	args = append(args, "--json")

	out, err := cobratree.RunCLICommand(ctx, recipeCLIPath, args)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return cobratree.ToolResultFromCLICommand(out), nil
}

// handlePreflightAGraphOffline runs the preflight_a_graph_offline recipe intent: The server has no validate-only endpoint, so this is the only dry run that does not consume a queue slot.
func handlePreflightAGraphOffline(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	if recipeCLIPathErr != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v", recipeCLIPathErr)), nil
	}

	input := req.GetArguments()
	args := []string{}
	args = append(args, "validate")
	var missingPath bool
	args, missingPath = appendRecipePositional(args, input["path"], true)
	if missingPath {
		return mcplib.NewToolResultError("path is required"), nil
	}
	args = append(args, "--json")

	out, err := cobratree.RunCLICommand(ctx, recipeCLIPath, args)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return cobratree.ToolResultFromCLICommand(out), nil
}

// handlePatchAGraphWithoutSilentlyHittingTheWrongNode runs the patch_a_graph_without_silently_hitting_the_wrong_node recipe intent: Refuses the write when node 6 no longer holds the expected class, which is how a template revision fails loudly rather than quietly.
func handlePatchAGraphWithoutSilentlyHittingTheWrongNode(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	if recipeCLIPathErr != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v", recipeCLIPathErr)), nil
	}

	input := req.GetArguments()
	args := []string{}
	args = append(args, "set")
	var missingPath bool
	args, missingPath = appendRecipePositional(args, input["path"], true)
	if missingPath {
		return mcplib.NewToolResultError("path is required"), nil
	}
	args = append(args, "6@CLIPTextEncode.text=a brass sextant")
	args = append(args, "--json")

	out, err := cobratree.RunCLICommand(ctx, recipeCLIPath, args)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return cobratree.ToolResultFromCLICommand(out), nil
}

var (
	recipeCLIPath    string
	recipeCLIPathErr error
)

func init() {
	recipeCLIPath, recipeCLIPathErr = cobratree.SiblingCLIPath()
}

func appendRecipePositional(args []string, value any, required bool) ([]string, bool) {
	selected := recipeValueString(value)
	if selected == "" {
		return args, required
	}
	return append(args, selected), false
}

func appendRecipeStringFlag(args []string, name string, value any, defaultValue string, required bool, useEquals bool) ([]string, bool) {
	selected := defaultValue
	if value != nil {
		selected = recipeValueString(value)
	}
	if selected == "" {
		return args, required
	}
	if useEquals {
		return append(args, "--"+name+"="+selected), false
	}
	return append(args, "--"+name, selected), false
}

func appendRecipeBoolFlag(args []string, name string, value any, defaultValue bool) []string {
	selected := defaultValue
	if v, ok := value.(bool); ok {
		selected = v
	}
	if selected {
		return append(args, "--"+name)
	}
	return args
}

func recipeValueString(value any) string {
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v)
	case float64:
		return formatMCPParamValue(v)
	case bool:
		if v {
			return "true"
		}
		return "false"
	default:
		if value == nil {
			return ""
		}
		return fmt.Sprintf("%v", value)
	}
}
