package leakgate

import "strings"

// Patterns turn the plaintext list into ERE lines for the operator's local
// pre-push hook, which scans the added lines of an outgoing push. Every letter
// of a sub, word, exact or phrase entry is a bracket class such as [Qq][Uu], so
// the patterns work whether or not the hook matches case-insensitively.
//
//	sub     the text
//	word    (^|[^A-Za-z])text([^A-Za-z]|$)
//	exact   (^|[^A-Za-z0-9])text([^A-Za-z0-9]|$)
//	phrase  the words joined by [^A-Za-z0-9]+
//	        (a one-letter first word, the drive-letter rule: w1:[^A-Za-z0-9]*w2...)
//	subcs   only its path-shaped forms, [/\\]text([/\\.]|$) and -d[= ]+text,
//	        written as the entry is: the hook's case behaviour is unknown and an
//	        -i hook would otherwise flag the product name
//
// The canary is never emitted.

const (
	patternBegin = "# BEGIN leak-gate patterns"
	patternEnd   = "# END leak-gate patterns"
	sepRun       = "[^A-Za-z0-9]+"
)

func bracket(s string) string {
	var b strings.Builder
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case isUpper(c):
			b.WriteString("[" + string(c) + string(c+32) + "]")
		case isLower(c):
			b.WriteString("[" + string(c-32) + string(c) + "]")
		default:
			b.WriteByte(c)
		}
	}
	return b.String()
}

// Patterns returns the ERE lines for the list, in list order.
func Patterns(es []Entry) []string {
	var out []string
	for _, e := range es {
		if e.Mode == ModeSub && e.Text == CanaryText() {
			continue
		}
		switch e.Mode {
		case ModeSub:
			out = append(out, bracket(e.Text))
		case ModeWord:
			out = append(out, "(^|[^A-Za-z])"+bracket(e.Text)+"([^A-Za-z]|$)")
		case ModeExact:
			out = append(out, "(^|[^A-Za-z0-9])"+bracket(e.Text)+"([^A-Za-z0-9]|$)")
		case ModeSubCS:
			out = append(out, `[/\\]`+e.Text+`([/\\.]|$)`, `-d[= ]+`+e.Text)
		case ModePhrase:
			words := strings.Fields(e.Text)
			for i := range words {
				words[i] = bracket(words[i])
			}
			if len(e.Text) > 1 && e.Text[1] == ' ' {
				out = append(out, words[0]+":[^A-Za-z0-9]*"+strings.Join(words[1:], sepRun))
			} else {
				out = append(out, strings.Join(words, sepRun))
			}
		}
	}
	return out
}

// PatternBlock is the pattern lines bracketed by BEGIN and END marker comments,
// so a re-run replaces the block (ReplaceBlock).
func PatternBlock(es []Entry) string {
	var b strings.Builder
	b.WriteString(patternBegin + " (generated by leakdigest; a re-run replaces this block)\n")
	for _, p := range Patterns(es) {
		b.WriteString(p + "\n")
	}
	b.WriteString(patternEnd + "\n")
	return b.String()
}

// ReplaceBlock puts block into existing: in place of the previous BEGIN to END
// block when there is one, at the end of the text otherwise. block uses LF; a
// text that uses CRLF gets the block with CRLF.
func ReplaceBlock(existing, block string) string {
	nl := "\n"
	if strings.Contains(existing, "\r\n") {
		nl = "\r\n"
		block = strings.ReplaceAll(block, "\n", "\r\n")
	}
	lines := strings.SplitAfter(existing, "\n")
	begin, end := -1, -1
	for i, l := range lines {
		t := strings.TrimRight(l, "\r\n")
		if begin < 0 && strings.HasPrefix(t, patternBegin) {
			begin = i
		} else if begin >= 0 && strings.HasPrefix(t, patternEnd) {
			end = i
			break
		}
	}
	if begin >= 0 && end >= 0 {
		return strings.Join(lines[:begin], "") + block + strings.Join(lines[end+1:], "")
	}
	if existing != "" && !strings.HasSuffix(existing, "\n") {
		existing += nl
	}
	return existing + block
}
