// node --test render/wf-qwen-image-21.test.mjs
import { test } from "node:test";
import assert from "node:assert";
import { readFileSync } from "node:fs";
import {
  buildQwenImage21, buildQwenImage21Edit,
  qwenImage21Sigmas, qwenImage21Mu, qwenImage21Tokens, formatSigmas, snapDim, rgbaPrompt,
  QWEN_IMAGE_21_RECIPE, QWEN_IMAGE_21_SCHEDULER, QWEN_IMAGE_21_MAX_REFS,
  RGBA_PROMPT_PREFIX, RGBA_PROMPT_SUFFIX,
} from "./wf-qwen-image-21.mjs";

// Generated by render/testdata/gen-qwen-image-21-sigmas.py with the REAL diffusers
// FlowMatchEulerDiscreteScheduler + the model repo's scheduler_config.json.
const GOLDEN = JSON.parse(readFileSync(new URL("./testdata/qwen-image-21-sigmas.golden.json", import.meta.url), "utf8"));

const base = {
  prompt: "a neon shop sign that reads \"QWEN IMAGE 2.1\", rainy night",
  unet: "qwen_image_2.1_bf16.safetensors",
  clip: "qwen3vl_8b_bf16.safetensors",
  vae: "qwen_image_2.1_vae_bf16.safetensors",
  seed: 42,
};

// ManualSigmas' own parser (comfy_extras/nodes_custom_sampler.py:1141).
const manualSigmasParse = (s) => (s.match(/[-+]?(?:\d*\.*\d+)/g) || []).map(Number);

const byClass = (g, cls) => Object.values(g).filter((n) => n.class_type === cls);
const one = (g, cls) => {
  const ns = byClass(g, cls);
  assert.equal(ns.length, 1, `exactly one ${cls}, got ${ns.length}`);
  return ns[0].inputs;
};

// Output counts per class, for the link audit (ComfyUI node definitions).
const OUTPUTS = {
  UNETLoader: 1, CLIPLoader: 1, VAELoader: 1, TextEncodeQwenImage21: 3, EmptyLatentImage: 1,
  RandomNoise: 1, BasicGuider: 1, CFGGuider: 1, KSamplerSelect: 1, ManualSigmas: 1,
  SamplerCustomAdvanced: 2, KSampler: 1, VAEDecode: 1, SplitImageWithAlpha: 2, SaveImage: 0,
  QwenImage21Cache: 1, LoadImage: 2, JoinImageWithAlpha: 1,
};

// Every [nodeId, outputIndex] input must name an existing node and an output it has.
function assertLinksResolve(g) {
  for (const [id, n] of Object.entries(g)) {
    assert.ok(n.class_type in OUTPUTS, `node ${id}: unexpected class ${n.class_type}`);
    for (const [k, v] of Object.entries(n.inputs)) {
      if (!Array.isArray(v)) continue;
      const [src, idx] = v;
      assert.ok(g[src], `node ${id}.${k} links to missing node ${src}`);
      assert.ok(idx < OUTPUTS[g[src].class_type], `node ${id}.${k} links to output ${idx} of ${g[src].class_type}, which has ${OUTPUTS[g[src].class_type]}`);
    }
  }
}

// --- the official schedule --------------------------------------------------

test("golden: JS sigmas match the real diffusers scheduler to 1e-6 for every committed case", () => {
  assert.ok(GOLDEN.cases.length >= 4, "fixture went blind");
  const want = new Set(["2048x2048/40", "1024x1024/40", "2752x1536/40", "1024x1024/25"]);
  for (const c of GOLDEN.cases) {
    want.delete(`${c.width}x${c.height}/${c.steps}`);
    const js = qwenImage21Sigmas({ width: c.width, height: c.height, steps: c.steps });
    assert.equal(js.length, c.sigmas.length, `${c.width}x${c.height}/${c.steps}: length`);
    assert.equal(js.length, c.steps + 1, "steps + the appended terminal 0");
    assert.ok(Math.abs(qwenImage21Mu(c.width, c.height) - c.mu) < 1e-9, `mu ${qwenImage21Mu(c.width, c.height)} vs ${c.mu}`);
    assert.equal(qwenImage21Tokens(c.width, c.height), c.tokens);
    for (let i = 0; i < js.length; i++) {
      assert.ok(Math.abs(js[i] - c.sigmas[i]) <= 1e-6,
        `${c.width}x${c.height}/${c.steps} sigma[${i}]: js ${js[i]} vs diffusers ${c.sigmas[i]}`);
    }
  }
  assert.deepEqual([...want], [], "every brief-named case must be in the fixture");
});

test("golden fixture was generated from the scheduler config the builder encodes", () => {
  const sc = GOLDEN.scheduler_config;
  assert.equal(sc.base_shift, QWEN_IMAGE_21_SCHEDULER.baseShift);
  assert.equal(sc.max_shift, QWEN_IMAGE_21_SCHEDULER.maxShift);
  assert.equal(sc.base_image_seq_len, QWEN_IMAGE_21_SCHEDULER.baseImageSeqLen);
  assert.equal(sc.max_image_seq_len, QWEN_IMAGE_21_SCHEDULER.maxImageSeqLen);
  assert.equal(sc.shift_terminal, QWEN_IMAGE_21_SCHEDULER.shiftTerminal);
  assert.equal(sc.time_shift_type, "exponential");
  assert.equal(sc.use_dynamic_shifting, true);
});

test("cross-check: the plan's hand-computed 2048x2048 / 40-step list (mu 1.3129)", () => {
  const appendixA = [1.000000, 0.992646, 0.985013, 0.977085, 0.968844, 0.960272, 0.951348, 0.942050, 0.932354, 0.922233,
    0.911660, 0.900604, 0.889030, 0.876901, 0.864177, 0.850811, 0.836756, 0.821955, 0.806348, 0.789868, 0.772438,
    0.753974, 0.734382, 0.713554, 0.691371, 0.667695, 0.642371, 0.615219, 0.586036, 0.554583, 0.520586, 0.483722,
    0.443614, 0.399813, 0.351785, 0.298886, 0.240336, 0.175179, 0.102230, 0.020000, 0.000000];
  const js = qwenImage21Sigmas({ width: 2048, height: 2048, steps: 40 });
  assert.equal(js.length, appendixA.length);
  js.forEach((v, i) => assert.ok(Math.abs(v - appendixA[i]) <= 6e-7, `sigma[${i}] ${v} vs ${appendixA[i]}`));
  assert.ok(Math.abs(qwenImage21Mu(2048, 2048) - 1.3129) < 1e-4);
});

test("schedule shape: starts at 1, ends at the terminal stretch then 0, strictly decreasing", () => {
  for (const [w, h, st] of [[2048, 2048, 40], [1024, 1024, 8], [256, 256, 3], [2752, 1536, 50]]) {
    const s = qwenImage21Sigmas({ width: w, height: h, steps: st });
    assert.ok(Math.abs(s[0] - 1) < 1e-12);
    assert.ok(Math.abs(s[s.length - 2] - QWEN_IMAGE_21_SCHEDULER.shiftTerminal) < 1e-12, "shift_terminal lands exactly");
    assert.equal(s[s.length - 1], 0);
    for (let i = 1; i < s.length; i++) assert.ok(s[i] < s[i - 1], `not decreasing at ${i}`);
  }
  assert.throws(() => qwenImage21Sigmas({ width: 1024, height: 1024, steps: 0 }), /steps must be a positive integer/);
});

test("formatSigmas: fixed-point only — ManualSigmas' regex has no exponent support", () => {
  const vals = [1, 0.5, 1e-7, 3.2e-9, 0];
  const s = formatSigmas(vals);
  assert.ok(!/e/i.test(s), `exponent leaked: ${s}`);
  const back = manualSigmasParse(s);
  assert.equal(back.length, vals.length, "every value parses as exactly one number");
  back.forEach((v, i) => assert.ok(Math.abs(v - vals[i]) < 1e-8));
  // What a naive String() join would have done to the parser: 1e-7 splits in two.
  assert.equal(manualSigmasParse(String(1e-7)).length, 2, "sanity: the parser really does split exponent form");
});

// --- T2I graph ----------------------------------------------------------------

test("T2I official: node classes, links, and the sigmas wired through ManualSigmas", () => {
  const g = buildQwenImage21({ ...base });
  assertLinksResolve(g);
  const types = Object.values(g).map((n) => n.class_type).sort();
  assert.deepEqual(types, ["BasicGuider", "CLIPLoader", "EmptyLatentImage", "KSamplerSelect", "ManualSigmas",
    "RandomNoise", "SamplerCustomAdvanced", "SaveImage", "SplitImageWithAlpha", "TextEncodeQwenImage21",
    "UNETLoader", "VAEDecode", "VAELoader"].sort());
  for (const banned of ["ModelSamplingAuraFlow", "EmptySD3LatentImage", "CLIPTextEncode", "ConditioningZeroOut", "CheckpointLoaderSimple", "KSampler"]) {
    assert.equal(byClass(g, banned).length, 0, `${banned} must not appear in the official T2I graph`);
  }
  assert.deepEqual(one(g, "UNETLoader"), { unet_name: base.unet, weight_dtype: "default" });
  assert.deepEqual(one(g, "CLIPLoader"), { clip_name: base.clip, type: "qwen_image", device: "default" });
  assert.deepEqual(one(g, "VAELoader"), { vae_name: base.vae });
  const enc = one(g, "TextEncodeQwenImage21");
  assert.deepEqual(enc, { clip: ["2", 0], prompt: base.prompt, negative_prompt: "", resolution: 1024 });
  assert.deepEqual(one(g, "RandomNoise"), { noise_seed: 42 });
  assert.deepEqual(one(g, "BasicGuider"), { model: ["1", 0], conditioning: ["4", 0] }, "conditioning = the positive");
  assert.deepEqual(one(g, "KSamplerSelect"), { sampler_name: "euler" });
  const sca = one(g, "SamplerCustomAdvanced");
  assert.deepEqual(sca, { noise: ["6", 0], guider: ["7", 0], sampler: ["8", 0], sigmas: ["9", 0], latent_image: ["5", 0] });
  const parsed = manualSigmasParse(one(g, "ManualSigmas").sigmas);
  const want = GOLDEN.cases.find((c) => c.width === 2048 && c.height === 2048 && c.steps === 40).sigmas;
  assert.equal(parsed.length, 41);
  parsed.forEach((v, i) => assert.ok(Math.abs(v - want[i]) <= 1e-6, `parsed sigma[${i}] ${v} vs ${want[i]}`));
  assert.deepEqual(one(g, "VAEDecode"), { samples: ["10", 0], vae: ["3", 0] });
});

test("T2I defaults: 2048x2048, 40 steps, cfg 1, euler/simple, opaque", () => {
  assert.deepEqual(QWEN_IMAGE_21_RECIPE, { steps: 40, cfg: 1.0, sampler: "euler", scheduler: "simple" });
  const g = buildQwenImage21({ ...base, schedule: "comfy" });
  assert.deepEqual(one(g, "EmptyLatentImage"), { width: 2048, height: 2048, batch_size: 1 });
  const ks = one(g, "KSampler");
  assert.equal(ks.steps, 40);
  assert.equal(ks.cfg, 1.0);
  assert.equal(ks.sampler_name, "euler");
  assert.equal(ks.scheduler, "simple");
  assert.equal(ks.denoise, 1.0);
  assert.equal(byClass(g, "SplitImageWithAlpha").length, 1, "opaque is the default");
});

test("T2I comfy schedule: KSampler(euler, simple) on the model's own shift — no custom-sampler nodes", () => {
  const g = buildQwenImage21({ ...base, schedule: "comfy" });
  assertLinksResolve(g);
  for (const gone of ["ManualSigmas", "SamplerCustomAdvanced", "BasicGuider", "CFGGuider", "RandomNoise", "KSamplerSelect", "ModelSamplingFlux", "ModelSamplingAuraFlow"]) {
    assert.equal(byClass(g, gone).length, 0, `${gone} must not appear in comfy mode`);
  }
  const ks = one(g, "KSampler");
  assert.deepEqual(ks, {
    seed: 42, steps: 40, cfg: 1.0, sampler_name: "euler", scheduler: "simple", denoise: 1.0,
    model: ["1", 0], positive: ["4", 0], negative: ["4", 1], latent_image: ["5", 0],
  });
  assert.deepEqual(one(g, "VAEDecode").samples, ["10", 0]);
});

test("T2I official with cfg != 1 guides with the negative (CFGGuider), not BasicGuider", () => {
  const g = buildQwenImage21({ ...base, negative: "blurry", steps: 40, cfg: 4 });
  assertLinksResolve(g);
  assert.equal(byClass(g, "BasicGuider").length, 0);
  assert.deepEqual(one(g, "CFGGuider"), { model: ["1", 0], positive: ["4", 0], negative: ["4", 1], cfg: 4 });
  assert.equal(one(g, "TextEncodeQwenImage21").negative_prompt, "blurry");
});

test("T2I steps drive the sigma count; sampler/scheduler pass through", () => {
  const g = buildQwenImage21({ ...base, steps: 25, cfg: 1.0, sampler: "euler_ancestral", width: 1024, height: 1024 });
  const parsed = manualSigmasParse(one(g, "ManualSigmas").sigmas);
  const want = GOLDEN.cases.find((c) => c.width === 1024 && c.height === 1024 && c.steps === 25).sigmas;
  assert.equal(parsed.length, 26);
  parsed.forEach((v, i) => assert.ok(Math.abs(v - want[i]) <= 1e-6));
  assert.equal(one(g, "KSamplerSelect").sampler_name, "euler_ancestral");
  const k = buildQwenImage21({ ...base, schedule: "comfy", scheduler: "beta" });
  assert.equal(one(k, "KSampler").scheduler, "beta");
});

test("dimension snap: DOWN to /32, floor 256; the official 2K sizes are untouched", () => {
  assert.equal(snapDim(2048), 2048);
  assert.equal(snapDim(2050), 2048);
  assert.equal(snapDim(2079), 2048);
  assert.equal(snapDim(1000), 992);
  assert.equal(snapDim(100), 256);
  for (const [w, h] of [[2048, 2048], [2400, 1792], [2528, 1696], [2752, 1536], [1536, 2752]]) {
    const g = buildQwenImage21({ ...base, width: w, height: h });
    assert.deepEqual(one(g, "EmptyLatentImage"), { width: w, height: h, batch_size: 1 });
  }
  const g = buildQwenImage21({ ...base, width: 1030, height: 777 });
  assert.deepEqual(one(g, "EmptyLatentImage"), { width: 1024, height: 768, batch_size: 1 });
  // The schedule is computed from the SNAPPED size, which is what the sampler sees.
  const parsed = manualSigmasParse(one(g, "ManualSigmas").sigmas);
  const want = qwenImage21Sigmas({ width: 1024, height: 768, steps: 40 });
  parsed.forEach((v, i) => assert.ok(Math.abs(v - want[i]) <= 1e-8));
  assert.throws(() => snapDim(0), /positive number/);
  assert.throws(() => snapDim(NaN), /positive number/);
  assert.throws(() => snapDim(20000), /exceeds ComfyUI's maximum/);
});

test("transparent: official RGBA prompt template, alpha kept (no SplitImageWithAlpha)", () => {
  const g = buildQwenImage21({ ...base, prompt: "A cute cartoon dragon sticker.", transparent: true });
  assertLinksResolve(g);
  assert.equal(one(g, "TextEncodeQwenImage21").prompt,
    "This is an RGBA image with transparency. A cute cartoon dragon sticker. The image has alpha channel and the background is transparent.",
    "verbatim QwenLM README template");
  assert.equal(byClass(g, "SplitImageWithAlpha").length, 0);
  assert.deepEqual(one(g, "SaveImage").images, ["11", 0], "SaveImage writes the 4-channel VAEDecode output");
  // Opaque: the alpha is split off before save.
  const o = buildQwenImage21({ ...base });
  assert.deepEqual(one(o, "SplitImageWithAlpha"), { image: ["11", 0] });
  assert.deepEqual(one(o, "SaveImage").images, ["12", 0]);
  assert.equal(one(o, "TextEncodeQwenImage21").prompt, base.prompt, "opaque prompts are never rewritten");
});

test("rgbaPrompt is idempotent and never doubles the period", () => {
  const once = rgbaPrompt("a red balloon");
  assert.equal(once, RGBA_PROMPT_PREFIX + "a red balloon" + RGBA_PROMPT_SUFFIX);
  assert.equal(rgbaPrompt(once), once);
  assert.equal(rgbaPrompt("a red balloon.  "), once);
  assert.ok(!rgbaPrompt("x...").includes(".."));
});

test("T2I validation: required files, builtin/gguf rejection, pair guard, enums", () => {
  assert.throws(() => buildQwenImage21({ ...base, prompt: "" }), /prompt is required/);
  assert.throws(() => buildQwenImage21({ ...base, unet: undefined }), /unet .* is required/);
  assert.throws(() => buildQwenImage21({ ...base, clip: "" }), /clip .* is required/);
  assert.throws(() => buildQwenImage21({ ...base, vae: undefined }), /vae .* is required/);
  assert.throws(() => buildQwenImage21({ ...base, vae: "builtin" }), /must name a file/);
  assert.throws(() => buildQwenImage21({ ...base, clip: "None" }), /must name a file/);
  assert.throws(() => buildQwenImage21({ ...base, unet: "qwen-image-2.1-Q8_0.gguf" }), /no GGUF loader/);
  assert.throws(() => buildQwenImage21({ ...base, steps: 20 }), /steps and cfg are a pair/);
  assert.throws(() => buildQwenImage21({ ...base, cfg: 3 }), /steps and cfg are a pair/);
  assert.throws(() => buildQwenImage21({ ...base, steps: 0, cfg: 1 }), /steps must be an integer/);
  assert.throws(() => buildQwenImage21({ ...base, steps: 20, cfg: 0 }), /cfg must be in/);
  assert.throws(() => buildQwenImage21({ ...base, schedule: "karras" }), /schedule must be one of official\|comfy/);
  assert.throws(() => buildQwenImage21({ ...base, resolution: 1000 }), /multiple of 32/);
  assert.throws(() => buildQwenImage21({ ...base, seed: -1 }), /seed must be/);
});

// --- edit graph -----------------------------------------------------------------

const editBase = { ...base, prompt: "put the shirt from <image2> on the person in <image1>", images: ["target.png", "shirt.png"] };

test("edit: N references wired as images.image_1..N in order; image_1 is the target; vae on the encoder", () => {
  for (const n of [1, 3, QWEN_IMAGE_21_MAX_REFS]) {
    const imgs = Array.from({ length: n }, (_, i) => `ref_${i + 1}.png`);
    const g = buildQwenImage21Edit({ ...editBase, images: imgs });
    assertLinksResolve(g);
    const loads = byClass(g, "LoadImage");
    assert.equal(loads.length, n, `${n} LoadImage nodes`);
    const enc = one(g, "TextEncodeQwenImage21");
    assert.deepEqual(enc.vae, ["3", 0], "vae must be wired or refs condition through the VL encoder only");
    assert.deepEqual(enc.clip, ["2", 0]);
    for (let i = 1; i <= n; i++) {
      const link = enc[`images.image_${i}`];
      assert.ok(link, `images.image_${i} wired`);
      assert.equal(g[link[0]].class_type, "LoadImage");
      assert.equal(g[link[0]].inputs.image, `ref_${i}.png`, `image_${i} must be images[${i - 1}]`);
    }
    assert.equal(enc[`images.image_${n + 1}`], undefined, "no dangling slot past N");
    const imageKeys = Object.keys(enc).filter((k) => k.startsWith("images."));
    assert.equal(imageKeys.length, n);
  }
});

test("edit: cache on the model path, sampler denoises the encoder's own latent (output 2)", () => {
  const g = buildQwenImage21Edit({ ...editBase, seed: 7 });
  assert.deepEqual(one(g, "QwenImage21Cache"), { model: ["1", 0], device: "auto", dtype: "default" });
  const ks = one(g, "KSampler");
  assert.deepEqual(ks, {
    seed: 7, steps: 40, cfg: 1.0, sampler_name: "euler", scheduler: "simple", denoise: 1.0,
    model: ["4", 0], positive: ["5", 0], negative: ["5", 1], latent_image: ["5", 2],
  });
  assert.equal(byClass(g, "EmptyLatentImage").length, 0, "any other latent size shifts the edit");
  assert.equal(one(g, "TextEncodeQwenImage21").resolution, 1024, "official default resolution");
  const c = buildQwenImage21Edit({ ...editBase, cacheDevice: "gpu", cacheDtype: "int8", resolution: 0 });
  assert.deepEqual(one(c, "QwenImage21Cache"), { model: ["1", 0], device: "gpu", dtype: "int8" });
  assert.equal(one(c, "TextEncodeQwenImage21").resolution, 0, "0 = keep each reference's own size");
  assert.equal(one(buildQwenImage21Edit({ ...editBase, resolution: 2048 }), "TextEncodeQwenImage21").resolution, 2048);
});

test("edit: transparent keeps source alpha (JoinImageWithAlpha per ref) and output alpha", () => {
  const g = buildQwenImage21Edit({ ...editBase, transparent: true });
  assertLinksResolve(g);
  const joins = byClass(g, "JoinImageWithAlpha");
  assert.equal(joins.length, 2);
  const enc = one(g, "TextEncodeQwenImage21");
  for (const i of [1, 2]) {
    const j = g[enc[`images.image_${i}`][0]];
    assert.equal(j.class_type, "JoinImageWithAlpha");
    assert.equal(g[j.inputs.image[0]].class_type, "LoadImage");
    assert.deepEqual(j.inputs.alpha, [j.inputs.image[0], 1], "LoadImage output 1 is the (inverted) alpha MASK");
  }
  assert.equal(byClass(g, "SplitImageWithAlpha").length, 0);
  const o = buildQwenImage21Edit({ ...editBase });
  assert.equal(byClass(o, "JoinImageWithAlpha").length, 0);
  assert.equal(byClass(o, "SplitImageWithAlpha").length, 1);
});

test("edit validation: ref count, cache enums, pair guard, required files", () => {
  assert.throws(() => buildQwenImage21Edit({ ...editBase, images: [] }), /images is required/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, images: undefined }), /images is required/);
  const eleven = Array.from({ length: QWEN_IMAGE_21_MAX_REFS + 1 }, (_, i) => `r${i}.png`);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, images: eleven }), /at most 10 images/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, images: ["a.png", ""] }), /images\[1\]/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, cacheDevice: "cuda" }), /cacheDevice must be one of/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, cacheDtype: "fp8" }), /cacheDtype must be one of/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, steps: 8 }), /steps and cfg are a pair/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, vae: "" }), /vae .* is required/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, resolution: 1000 }), /multiple of 32/);
  assert.throws(() => buildQwenImage21Edit({ ...editBase, prompt: " " }), /prompt is required/);
});
