// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — intent handlers.
//
// Intents are higher-level MCP tools that compose multiple endpoint calls
// or expose curated recipe commands with useful flag defaults.
// Rather than forcing an agent to stitch primitives like get_thread +
// create_issue + link_attachment, a single create_issue_from_thread tool
// accepts the top-level input, calls each endpoint in sequence, resolves
// bindings between steps, and returns the final captured value.
//
// Each intent is emitted as a handler registered alongside (or in place of,
// when MCP.EndpointTools == "hidden") the raw endpoint-mirror tools.

package mcp

import (
	"context"
	"fmt"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"llamaswap-pp-cli/internal/mcp/bound"
	"llamaswap-pp-cli/internal/mcp/cobratree"
)

// RegisterIntents adds generated intent tools to the MCP server.
// This is called from RegisterTools when spec intents or recipe-lifted intents exist.
func RegisterIntents(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("free_vram_safely_before_a_render_job",
			mcplib.WithDescription("Drains in-flight work first and always excludes the protected keep-set, then confirms via /running."),
			mcplib.WithBoolean("all", mcplib.Description("Override the recipe's --all value.")),
			mcplib.WithBoolean("drain", mcplib.Description("Override the recipe's --drain value.")),
		),
		handleFreeVramSafelyBeforeARenderJob,
	)
	s.AddTool(
		mcplib.NewTool("prove_the_memory_stack_survived_a_config_change",
			mcplib.WithDescription("Asserts embedder cosine and reranker score against stored calibrated baselines — catches dropped flags roster checks miss."),
			mcplib.WithBoolean("probe", mcplib.Description("Override the recipe's --probe value.")),
		),
		handleProveTheMemoryStackSurvivedAConfigChange,
	)
}

// handleFreeVramSafelyBeforeARenderJob runs the free_vram_safely_before_a_render_job recipe intent: Drains in-flight work first and always excludes the protected keep-set, then confirms via /running.
func handleFreeVramSafelyBeforeARenderJob(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	if recipeCLIPathErr != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v", recipeCLIPathErr)), nil
	}

	input := req.GetArguments()
	args := []string{}
	args = append(args, "unload")
	args = appendRecipeBoolFlag(args, "all", input["all"], true)
	args = appendRecipeBoolFlag(args, "drain", input["drain"], true)
	args = append(args, "--json")

	out, err := cobratree.RunCLICommand(ctx, recipeCLIPath, args)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(bound.Text(out)), nil
}

// handleProveTheMemoryStackSurvivedAConfigChange runs the prove_the_memory_stack_survived_a_config_change recipe intent: Asserts embedder cosine and reranker score against stored calibrated baselines — catches dropped flags roster checks miss.
func handleProveTheMemoryStackSurvivedAConfigChange(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	if recipeCLIPathErr != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("companion CLI binary not found: %v", recipeCLIPathErr)), nil
	}

	input := req.GetArguments()
	args := []string{}
	args = append(args, "verify")
	args = appendRecipeBoolFlag(args, "probe", input["probe"], true)
	args = append(args, "--json")

	out, err := cobratree.RunCLICommand(ctx, recipeCLIPath, args)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(bound.Text(out)), nil
}

var (
	recipeCLIPath    string
	recipeCLIPathErr error
)

func init() {
	recipeCLIPath, recipeCLIPathErr = cobratree.SiblingCLIPath()
}

func appendRecipePositional(args []string, value any, required bool) ([]string, bool) {
	selected := recipeValueString(value)
	if selected == "" {
		return args, required
	}
	return append(args, selected), false
}

func appendRecipeStringFlag(args []string, name string, value any, defaultValue string, required bool, useEquals bool) ([]string, bool) {
	selected := defaultValue
	if value != nil {
		selected = recipeValueString(value)
	}
	if selected == "" {
		return args, required
	}
	if useEquals {
		return append(args, "--"+name+"="+selected), false
	}
	return append(args, "--"+name, selected), false
}

func appendRecipeBoolFlag(args []string, name string, value any, defaultValue bool) []string {
	selected := defaultValue
	if v, ok := value.(bool); ok {
		selected = v
	}
	if selected {
		return append(args, "--"+name)
	}
	return args
}

func recipeValueString(value any) string {
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v)
	case float64:
		return formatMCPParamValue(v)
	case bool:
		if v {
			return "true"
		}
		return "false"
	default:
		if value == nil {
			return ""
		}
		return fmt.Sprintf("%v", value)
	}
}
