// Copyright 2026 Daniel Martinez and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"llamaswap-pp-cli/internal/cli"
	"llamaswap-pp-cli/internal/platform"
)

const mcpTenantGateOwnerKey = "pp:tenant-gate"

var verifyFreshMCPInvocation = cli.VerifyMCPInvocation

// installFreshTenantGate wraps every tool registered on this server,
// including tools added by later code-orchestration and intent registrars.
// Cobra mirrors are the sole exception: the child CLI owns their one live
// tenant gate.
func installFreshTenantGate(s *server.MCPServer) {
	s.Use(func(next server.ToolHandlerFunc) server.ToolHandlerFunc {
		return requireFreshTenantGate(s, next)
	})
}

func requireFreshTenantGate(s *server.MCPServer, next server.ToolHandlerFunc) server.ToolHandlerFunc {
	return func(ctx context.Context, request mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		if entry := s.GetTool(request.Params.Name); entry != nil && entry.Tool.Meta != nil && entry.Tool.Meta.AdditionalFields != nil {
			if owner, _ := entry.Tool.Meta.AdditionalFields[mcpTenantGateOwnerKey].(string); owner == "child-cli" {
				return next(ctx, request)
			}
		}
		session, err := verifyFreshMCPInvocation(ctx)
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}
		if session == nil {
			// A nil session with a nil error means this CLI registers no
			// tenant-gated platform source, so there is no tenant to gate on.
			// cli.VerifyMCPInvocation returns that pair ONLY on that branch —
			// once a source is registered it returns either a verified session
			// or an error — so continuing here cannot skip a gate that exists.
			// cli.BindMCPClient already reads the pair that way for the typed
			// client path; rejecting it here instead made every in-process tool
			// permanently unreachable on a CLI with no platform source, which
			// is the whole code-orchestration surface.
			return next(ctx, request)
		}
		defer session.ZeroCredentials()
		return next(platform.ContextWithSession(ctx, session), request)
	}
}
